name: 'Simple workflow that needs approval to continue'

on:
  workflow_dispatch:

jobs:
  job-with-approval:
    runs-on: ubuntu-latest
    ## We must configure the environment "development" and the required approvals
    environment: development
    steps:
      - run: echo "Hello World! I ran because someone approved it"