name: 'Checkout code from other repository'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: felipe-leon-NTT/juice-shop
          ref: featureX
          path: juice-shop-ck
      - run: pwd
      - run: ls -l
      