name: 'Checkout code from other repository'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out code from other repo'
        uses: actions/checkout@v4
        with:
          ## Repo to checkout
          repository: felipe-leon-NTT/juice-shop
          ## Reference: branch, tag, etc
          ref: featureX
          ## Download folder
          path: juice-shop-ck
      - run: pwd
      - run: ls -l juice-shop-ck
      