name: 'Workflow with a job that has two steps that are going to run always'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: first-step
        run: exit 1
      - if: ${{ failure() && steps.first-step.outcome == 'failure' }}
        run: |
          echo "Hello World! I will run always"
          echo "::debug::(The first step failed)" # This echo will be only printed in the ACTIONS_STEP_DEBUG is set to true in repo env vars
      