name: 'Custom actions - Testing a container action'

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Using custom container action
        id: greeting-message
        uses: felipe-leon-NTT/testing-custom-container-action@v0.0.5
        with:
          name: Felipe
      - run: echo ${{ steps.greeting-message.outputs.msg }}