name: 'Passing values between two jobs'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.first_step.outputs.passing_value }}
    steps:
      - id: first_step
        run: echo "passing_value=iamgonnabepassed" >> $GITHUB_OUTPUT
      - run: echo "PASSING_VALUE=iamgonnabepassedtoo" >> $GITHUB_ENV
  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      GITHUB_NEEDS: ${{ toJSON(needs) }}
    steps:
      - name: 'Print value'
        run: echo ${{ needs.job1.outputs.output1 }}
      - run: echo $GITHUB_NEEDS
      - run: echo ${{ env.PASSING_VALUE }}
      