name: 'Passing values between two jobs'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: first_step
        run: echo "passing_value=iamgonnabepassed" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Print value'
        run: echo ${{ jobs.job1.steps.first.step.passing_value }}
    