name: 'Trying the service containers feature'

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: 'Wait for service (PostgreSQL) to be ready'
        run: |
          until pg_isready -h localhost -p 5432 -U user; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done
      - name: 'Test database connection'
        run: |
          PGPASSWORD=password psql -h localhost -U user -d testdb -c '\l'