name: "Simple workflow that runs on every push"

on:
  push:
    #paths:
    #  - '!.github/**'
    branches:
      - 'main'

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"