name: "Strategy - Matrix using include"

on:
  workflow_dispatch:

jobs:
  using-include:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     color: ['blue', 'red']
    #     severity: ['high', 'medium', 'low']
    #     include:
    #       - severity: 'urgent'
    #         user: fleonfer
    #       - severity: 'high'
    #         user: 'secondincharge'
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - name: Print matrix combinations
        run: echo "${{ toJSON(matrix) }}"
