name: "Strategy - Matrix using include"

on:
  workflow_dispatch:

jobs:
  using-include:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: ['blue', 'red']
        severity: ['high', 'medium', 'low']
        include:
          - user: fleonfer
    steps:
      - run: |
          echo "Color: ${{ matrix.color }} | Severity: ${{ matrix.severity }} | User: ${{ matrix.user }}"
