name: "Strategy - Matrix using include"

on:
  workflow_dispatch:

jobs:
  using-include:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: ['blue', 'red']
        severity: ['high', 'medium', 'low']
        include:
          - user: bot
          - severity: 'high'
            user: fleonfer
    steps:
      - name: Print matrix combinations
        run: echo "${{ toJSON(matrix) }}"
