name: 'Triggering - Run a workflow when other one runs'

on:
  workflow_run:
    workflows: ["Simple workflow that runs on every push"]
    types: [completed]
    branches:
      - 'main'
      - 'testing-trigger'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: exit 2
      - run: echo "Hello, World! I ran because a particular workflow was successfully executed"
