name: 'Triggering - Run a workflow when a reference (branch or tag) is created'

on:
  create:

jobs:
  hello-on-branch-creation:
    if: ${{ github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World! I am here because a new reference of type 'branch' was created"

  hello-on-tag-creation:
    if: ${{ github.event.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World! I am here because a new reference of type 'tag' was created"