name: 'Triggering - Run a workflow when a pull request is opened'

on:
  pull_request_target:
    types:
      - 'opened'
      - 'closed'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World! I ran because a pull request was opened"
