name: 'Triggering - Run a workflow from outside of GH'

on:
  repository_dispatch:

jobs:
  polite-greeting:
    runs-on: ubuntu-latest
    if: ${{ github.event.polite }}
    steps:
      - run: echo "Hello, Mr. ${{ github.event.name }}"
  impolite-greeting:
    runs-on: ubuntu-latest
    if: ${{ !github.event.polite }}
    steps:
      - run: echo "Hi, ${{ github.event.name }}!"