name: 'Triggering - Run a workflow with the context of the base branch (pull_request_target)'

on:
  pull_request_target:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World! I ran because a pull request was opened and I have the context of the base branch"
      - name: Checkout code
        uses: actions/checkout@v2
      - run: ls -l
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: sleep 60s