name: 'Triggering - Run job based on a check run activity'

on:
  check_run:
    types: [completed, rerequested, completed, requested_action]

jobs:
  jobs1:
    runs-on: ubuntu-latest
    run: echo "Hello, World!"