##
##  To test this workflow you have to run this command (you can change the client_payload values) in 
##  a terminal using cURL or use a tool like Postman:
##  
##  curl --location 'https://api.github.com/repos/felipe-leon-NTT/hello-world/dispatches' \
##  --header 'Accept: application/vnd.github+json' \
##  --header 'X-GitHub-Api-Version: 2022-11-28' \
##  --header 'Content-Type: application/json' \
##  --header 'Authorization: ••••••' \
##  --data '{"event_type":"on-demand-test","client_payload":{"name":"Felipe","polite":false}}'
##

name: 'Triggering - Run a workflow from outside of GH'

on:
  repository_dispatch:

jobs:
  polite-greeting:
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.polite }}
    steps:
      - run: echo "Hello, Mr. ${{ github.event.client_payload.name }}"
  impolite-greeting:
    runs-on: ubuntu-latest
    if: ${{ !github.event.client_payload.polite }}
    steps:
      - run: echo "Hi, ${{ github.event.client_payload.name }}!"